config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount Iconsole::Engine, at: '/'
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  # devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }

  get 'home/dashboard'
  get 'home/planning'
  get 'home/setting'
  get 'home/sharing'


  resources :user_profiles
  resources :holds
  resources :trades
  resources :stoploss_frames

  # Defines the root path route ("/")
  root "home#dashboard"
end

app/views/layouts/shared/_alert.html.slim
#page-alert-content.alert.alert-info.alert-dismissible.fade.show[role="alert"]
  strong
    | Welcome to tradelog!
  |  You have a great work today. 

  / button.btn-close[type="button" data-bs-dismiss="alert" aria-label="Close"]

app/views/layouts/shared/_footer.html.slim
span.text-muted.d-block.text-center
  | Copyright © trading.com 2023
  

app/views/layouts/shared/_head_logo.html.slim
.sidebar-brand-wrapper.d-none.d-lg-flex.align-items-center.justify-content-center.fixed-top
  = link_to root_path, class: "sidebar-brand brand-logo" do
    span.text-success tradelog.info
  = link_to root_path, class: "sidebar-brand brand-logo-mini" do
    = image_tag("plugin/logo-mini.svg")

app/views/layouts/shared/_head_logo_mini.html.slim
.navbar-brand-wrapper.d-flex.d-lg-none.align-items-center.justify-content-center
  a.navbar-brand.brand-logo-mini[href="index.html"]
    / = image_tag("plugin/logo-mini.svg")
    span.text-success tradelog

app/views/layouts/shared/_head_nav_menu.html.slim
.navbar-menu-wrapper.flex-grow.d-flex.align-items-stretch
  button.navbar-toggler.navbar-toggler.align-self-center[type="button" data-toggle="minimize"]
    span.mdi.mdi-menu
  
  ul.navbar-nav.navbar-nav-right
    li.nav-item.dropdown.d-none.d-lg-block
      = link_to new_trade_path, class: 'btn btn-success' do
        span = I18n.t('button.trade.create_new_trade')

    / li.nav-item.nav-settings.d-none.d-lg-block
    /   a.nav-link[href="#"]
    /     i.mdi.mdi-view-grid
    / li.nav-item.dropdown.border-left
    /   a#messageDropdown.nav-link.count-indicator.dropdown-toggle[href="#" data-toggle="dropdown" aria-expanded="false"]
    /     i.mdi.mdi-email
    /     span.count.bg-success
    / li.nav-item.dropdown.border-left
    /   a#notificationDropdown.nav-link.count-indicator.dropdown-toggle[href="#" data-toggle="dropdown"]
    /     i.mdi.mdi-bell
    /     span.count.bg-danger
   
    / li.nav-item.dropdown.border-left
    /   a#notificationDropdown.nav-link.count-indicator.dropdown-toggle[href="#" data-toggle="dropdown"]
    /     i.mdi.mdi-settings.text-success
    /     span.count.bg-danger


    / li.nav-item.dropdown.border-left
    /   a#notificationDropdown.nav-link.count-indicator.dropdown-toggle[href="#" data-toggle="dropdown"]
    /     i.mdi.mdi-logout.text-danger
    /     span.count.bg-danger
    / li.nav-item.dropdown.border-left
    /   a#notificationDropdown.nav-link.count-indicator.dropdown-toggle[href="#" data-toggle="dropdown"]
    /     span.mdi.mdi-format-line-spacing
    /     span.count.bg-danger

    / li.nav-item.dropdown.border-left
    /   a#notificationDropdown.nav-link.count-indicator.dropdown-toggle[href="#" data-toggle="dropdown"]
    /     i.mdi.mdi-calendar.text-success
    /     span.count.bg-danger

    / li.nav-item.dropdown.border-left
    /   a#notificationDropdown.nav-link.count-indicator.dropdown-toggle[href="#" data-toggle="dropdown"]
    /     i.mdi.mdi-menu-down.d-none.d-sm-block
    /     span.count.bg-danger




    li.nav-item.dropdown.border-left
      - change_locale = locale == "vi".to_sym ? 'en' : 'vi'
      = link_to request.params.merge(locale: change_locale), class: 'btn btn-link' do
        span.text-white =<> change_locale.upcase


    - if user_signed_in?
      li.nav-item.dropdown
        a#profileDropdown.nav-link[href="#" data-toggle="dropdown"]
          .navbar-profile
            = image_tag("plugin/faces/face15.jpg", class: "img-xs rounded-circle" )
            p.mb-0.d-none.d-sm-block.navbar-profile-name
              = current_user.name || current_user.email
            i.mdi.mdi-menu-down.d-none.d-sm-block
        .dropdown-menu.dropdown-menu-right.navbar-dropdown.preview-list[aria-labelledby="profileDropdown"]
          h6.p-3.mb-0
            | Tài khoản
          .dropdown-divider
          = link_to user_profile_path(current_user.profile_id), class: 'dropdown-item preview-item' do
            .preview-thumbnail
              .preview-icon.bg-dark.rounded-circle
                i.mdi.mdi-settings.text-success
            .preview-item-content
              p.preview-subject.mb-1
                | Thông tin tài khoản

          / .dropdown-divider
          / a.dropdown-item.preview-item
          /   .preview-thumbnail
          /     .preview-icon.bg-dark.rounded-circle
          /       i.mdi.mdi-settings.text-success
          /   .preview-item-content
          /     p.preview-subject.mb-1
          /       | Settings
          / .dropdown-divider
          / = link_to edit_user_password_path(current_user), class: 'dropdown-item preview-item' do
          /   .preview-thumbnail
          /     .preview-icon.bg-dark.rounded-circle
          /       i.mdi.mdi-logout.text-danger
          /   .preview-item-content
          /     p.preview-subject.mb-1
          /       | Change Password


          .dropdown-divider
          = link_to destroy_user_session_path, :method => :delete, :data => { :no_turbolink => true }, class: 'dropdown-item preview-item' do
            .preview-thumbnail
              .preview-icon.bg-dark.rounded-circle
                i.mdi.mdi-logout.text-danger
            .preview-item-content
              p.preview-subject.mb-1
                | Logout
   
    - else
      li.nav-item.dropdown
        = link_to new_user_session_path, class: 'nav-link' do
          .navbar-profile
            = image_tag("plugin/faces/face15.jpg", class: "img-xs rounded-circle" )
            p.mb-0.d-none.d-sm-block.navbar-profile-name
              | Demo Account

app/views/layouts/shared/_left_side_menu.html.slim
ul.nav
  li.nav-item.menu-items
    = link_to home_dashboard_path, class: "nav-link" do
      span.menu-icon
        i.mdi.mdi-speedometer
      span.menu-title
        | Dashboard
  li.nav-item.menu-items
    = link_to trades_path, class: "nav-link" do
      span.menu-icon
        i.mdi.mdi-playlist-play
      span.menu-title
        | Trading
  li.nav-item.menu-items
    = link_to holds_path, class: "nav-link" do
      span.menu-icon
        i.mdi.mdi-playlist-play
      span.menu-title
        | Holding
  li.nav-item.menu-items
    = link_to home_planning_path, class: "nav-link" do
      span.menu-icon
        i.mdi.mdi-playlist-play
      span.menu-title
        | Planning
  li.nav-item.menu-items
    = link_to home_sharing_path, class: "nav-link" do
      span.menu-icon
        i.mdi.mdi-playlist-play
      span.menu-title
        | Sharing
  li.nav-item.menu-items
    = link_to home_setting_path, class: "nav-link" do
      span.menu-icon
        i.mdi.mdi-playlist-play
      span.menu-title
        | Setting

  li.nav-item.menu-items
    a.nav-link[data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic"]
      span.menu-icon
        i.mdi.mdi-laptop
      span.menu-title
        | Basic UI Elements
      i.menu-arrow
    #ui-basic.collapse
      ul.nav.flex-column.sub-menu
        li.nav-item
          a.nav-link[href="pages/ui-features/buttons.html"]
            | Buttons
        li.nav-item
          a.nav-link[href="pages/ui-features/dropdowns.html"]
            | Dropdowns
        li.nav-item
          a.nav-link[href="pages/ui-features/typography.html"]
            | Typography
  
  li.nav-item.menu-items
    a.nav-link[href="pages/tables/basic-table.html"]
      span.menu-icon
        i.mdi.mdi-table-large
      span.menu-title
        | Tables
  li.nav-item.menu-items
    a.nav-link[href="pages/charts/chartjs.html"]
      span.menu-icon
        i.mdi.mdi-chart-bar
      span.menu-title
        | Charts
  li.nav-item.menu-items
    a.nav-link[href="pages/icons/mdi.html"]
      span.menu-icon
        i.mdi.mdi-contacts
      span.menu-title
        | Icons
  li.nav-item.menu-items
    a.nav-link[data-toggle="collapse" href="#auth" aria-expanded="false" aria-controls="auth"]
      span.menu-icon
        i.mdi.mdi-security
      span.menu-title
        | User Pages
      i.menu-arrow
    #auth.collapse
      ul.nav.flex-column.sub-menu
        li.nav-item
          a.nav-link[href="pages/samples/blank-page.html"]
            |  Blank Page 
        li.nav-item
          a.nav-link[href="pages/samples/error-404.html"]
            |  404 
        li.nav-item
          a.nav-link[href="pages/samples/error-500.html"]
            |  500 
        li.nav-item
          a.nav-link[href="pages/samples/login.html"]
            |  Login 
        li.nav-item
          a.nav-link[href="pages/samples/register.html"]
            |  Register 
  li.nav-item.menu-items
    a.nav-link[href="http://www.bootstrapdash.com/demo/corona-free/jquery/documentation/documentation.html"]
      span.menu-icon
        i.mdi.mdi-file-document-box
      span.menu-title
        | Documentation