config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount Iconsole::Engine, at: '/'
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  # devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }

  get 'home/dashboard'
  get 'home/planning'
  get 'home/setting'
  get 'home/sharing'


  resources :user_profiles
  resources :holds
  resources :trades
  resources :stoploss_frames

  # Defines the root path route ("/")
  root "home#dashboard"
end

app/models/hold.rb
# == Schema Information
#
# Table name: holds
#
#  id            :bigint           not null, primary key
#  user_id       :bigint
#  symbol        :string
#  coin_name     :string
#  target        :decimal(, )
#  volume_size   :decimal(, )
#  volume_amount :decimal(, )
#  entry_price   :decimal(, )
#  status        :integer
#  take_profit   :decimal(, )
#  note          :text
#  description   :text
#  entry_photo   :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class Hold < ApplicationRecord
end

app/controllers/holds_controller.rb
class HoldsController < ApplicationController
  before_action :set_hold, only: %i[ show edit update destroy ]

  # GET /holds or /holds.json
  def index
    @holds = Hold.all
  end

  # GET /holds/1 or /holds/1.json
  def show
  end

  # GET /holds/new
  def new
    @hold = Hold.new
  end

  # GET /holds/1/edit
  def edit
  end

  # POST /holds or /holds.json
  def create
    @hold = Hold.new(hold_params)

    respond_to do |format|
      if @hold.save
        format.html { redirect_to hold_url(@hold), notice: "Hold was successfully created." }
        format.json { render :show, status: :created, location: @hold }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hold.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /holds/1 or /holds/1.json
  def update
    respond_to do |format|
      if @hold.update(hold_params)
        format.html { redirect_to hold_url(@hold), notice: "Hold was successfully updated." }
        format.json { render :show, status: :ok, location: @hold }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hold.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holds/1 or /holds/1.json
  def destroy
    @hold.destroy

    respond_to do |format|
      format.html { redirect_to holds_url, notice: "Hold was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hold
      @hold = Hold.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hold_params
      params.require(:hold).permit(:user_id, :symbol, :coin_name, :target, :volume_size, :volume_amount, :entry_price, :status, :take_profit, :note, :description, :entry_photo)
    end
end

app/helpers/holds_helper.rb
module HoldsHelper
end

app/views/holds/_form.html.slim
= simple_form_for(@hold) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :user_id
    = f.input :symbol
    = f.input :coin_name
    = f.input :target
    = f.input :volume_size
    = f.input :volume_amount
    = f.input :entry_price
    = f.input :status
    = f.input :take_profit
    = f.input :note
    = f.input :description
    = f.input :entry_photo

  .form-actions
    = f.button :submit

app/views/holds/_hold.html.slim
div id="#{dom_id hold}"
  p
    strong User:
    =< hold.user_id
  p
    strong Symbol:
    =< hold.symbol
  p
    strong Coin name:
    =< hold.coin_name
  p
    strong Target:
    =< hold.target
  p
    strong Volume size:
    =< hold.volume_size
  p
    strong Volume amount:
    =< hold.volume_amount
  p
    strong Entry price:
    =< hold.entry_price
  p
    strong Status:
    =< hold.status
  p
    strong Take profit:
    =< hold.take_profit
  p
    strong Note:
    =< hold.note
  p
    strong Description:
    =< hold.description
  p
    strong Entry photo:
    =< hold.entry_photo

app/views/holds/edit.html.slim
h1 Editing hold

== render "form", hold: @hold

br

div
  => link_to "Show this hold", @hold
  '|
  =< link_to "Back to holds", holds_path

app/views/holds/index.html.slim
.holding-content
  h1 Holding
  .row
    .col-md-4.col-xl-4.grid-margin.stretch-card
      = render "holds/shared/porfolio_piechart"
    .col-md-8.col-xl-8.grid-margin.stretch-card
      = render "holds/shared/holding_barchart"
  .row
    .col-md-12.col-xl-12.grid-margin.stretch-card
      = render "home/shared/holding_entry"
  .row
    .col-md-4
      = render "home/shared/potential"
    .col-md-8.col-xl-8.grid-margin.stretch-card
      .card
        .card-body
          h4.card-title
            | Following
          p Danh sách các Altcoins đang theo dõi

app/views/holds/new.html.slim
h1 New hold

== render "form", hold: @hold

br

div
  = link_to "Back to holds", holds_path

app/views/holds/show.html.slim
p style="color: green" = notice

== render @hold

div
  => link_to "Edit this hold", edit_hold_path(@hold)
  '|
  =< link_to "Back to holds", holds_path

  = button_to "Destroy this hold", @hold, method: :delete