config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount Iconsole::Engine, at: '/'
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  # devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }

  get 'home/dashboard'
  get 'home/planning'
  get 'home/setting'
  get 'home/sharing'


  resources :user_profiles
  resources :holds
  resources :trades
  resources :stoploss_frames

  # Defines the root path route ("/")
  root "home#dashboard"
end

app/models/stoploss_frame.rb
# == Schema Information
#
# Table name: stoploss_frames
#
#  id                :bigint           not null, primary key
#  name              :string
#  percentage_number :float
#  percentage_max    :float
#  percentage_min    :float
#  transaction_type  :integer
#  description       :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
class StoplossFrame < ApplicationRecord
end

app/controllers/stoploss_frames_controller.rb
class StoplossFramesController < ApplicationController
  before_action :set_stoploss_frame, only: %i[ show edit update destroy ]

  # GET /stoploss_frames or /stoploss_frames.json
  def index
    @stoploss_frames = StoplossFrame.all
  end

  # GET /stoploss_frames/1 or /stoploss_frames/1.json
  def show
  end

  # GET /stoploss_frames/new
  def new
    @stoploss_frame = StoplossFrame.new
  end

  # GET /stoploss_frames/1/edit
  def edit
  end

  # POST /stoploss_frames or /stoploss_frames.json
  def create
    @stoploss_frame = StoplossFrame.new(stoploss_frame_params)

    respond_to do |format|
      if @stoploss_frame.save
        format.html { redirect_to stoploss_frame_url(@stoploss_frame), notice: "Stoploss frame was successfully created." }
        format.json { render :show, status: :created, location: @stoploss_frame }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stoploss_frame.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stoploss_frames/1 or /stoploss_frames/1.json
  def update
    respond_to do |format|
      if @stoploss_frame.update(stoploss_frame_params)
        format.html { redirect_to stoploss_frame_url(@stoploss_frame), notice: "Stoploss frame was successfully updated." }
        format.json { render :show, status: :ok, location: @stoploss_frame }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stoploss_frame.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stoploss_frames/1 or /stoploss_frames/1.json
  def destroy
    @stoploss_frame.destroy

    respond_to do |format|
      format.html { redirect_to stoploss_frames_url, notice: "Stoploss frame was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stoploss_frame
      @stoploss_frame = StoplossFrame.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stoploss_frame_params
      params.require(:stoploss_frame).permit(:name, :percentage_number, :percentage_max, :percentage_min, :transaction_type, :description)
    end
end

app/helpers/stoploss_frames_helper.rb
module StoplossFramesHelper
end

app/views/stoploss_frames/_form.html.slim
= simple_form_for(@stoploss_frame) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :percentage_number
    = f.input :percentage_max
    = f.input :percentage_min
    = f.input :transaction_type
    = f.input :description

  .form-actions
    = f.button :submit

app/views/stoploss_frames/_stoploss_frame.html.slim
div id="#{dom_id stoploss_frame}"
  p
    strong Name:
    =< stoploss_frame.name
  p
    strong Percentage number:
    =< stoploss_frame.percentage_number
  p
    strong Percentage max:
    =< stoploss_frame.percentage_max
  p
    strong Percentage min:
    =< stoploss_frame.percentage_min
  p
    strong Transaction type:
    =< stoploss_frame.transaction_type
  p
    strong Description:
    =< stoploss_frame.description

app/views/stoploss_frames/edit.html.slim
h1 Editing stoploss frame

== render "form", stoploss_frame: @stoploss_frame

br

div
  => link_to "Show this stoploss frame", @stoploss_frame
  '|
  =< link_to "Back to stoploss frames", stoploss_frames_path

app/views/stoploss_frames/index.html.slim
p style="color: green" = notice

h1 Stoploss frames

#stoploss_frames
  - @stoploss_frames.each do |stoploss_frame|
    == render stoploss_frame
    p
      = link_to "Show this stoploss frame", stoploss_frame

= link_to "New stoploss frame", new_stoploss_frame_path

app/views/stoploss_frames/new.html.slim
h1 New stoploss frame

== render "form", stoploss_frame: @stoploss_frame

br

div
  = link_to "Back to stoploss frames", stoploss_frames_path

app/views/stoploss_frames/show.html.slim
p style="color: green" = notice

== render @stoploss_frame

div
  => link_to "Edit this stoploss frame", edit_stoploss_frame_path(@stoploss_frame)
  '|
  =< link_to "Back to stoploss frames", stoploss_frames_path

  = button_to "Destroy this stoploss frame", @stoploss_frame, method: :delete